name: Build and Deploy to AWS S3

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'
      - 'css/**'
      - 'js/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to S3
        uses: aws-actions/configure-aws-credentials@v2
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-2

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://suki-site --exclude ".git/*" --exclude ".github/*" --exclude "node_modules/*" --exclude "README.md" --exclude "LICENSE"
          aws s3 cp index.html s3://suki-site/index.html --cache-control "max-age=0, no-cache, no-store, must-revalidate"
          aws s3 cp css/ s3://suki-site/css/ --recursive
          aws s3 cp js/ s3://suki-site/js/ --recursive